### PR TITLE
Added new endpoints and converted character key in members array to characterEntity 

### PR DESCRIPTION
**Pull request by morloderex**
* Gathered new fixtures and fixed failed tests for them.
* Added Mount endpoint
* Converted character key within members array to CharacterEntity class if members field is set while requesting a guild.

### CODE REVIEW

**Comment by morloderex** [comment]
@jyggen Ping Please merge this PR

**Comment by jyggen** [comment]
Could you please rename the namespace to `Pwnraid\Bnet\Warcraft\Mounts` (and `Pwnraid\Bnet\Test\Warcraft\Mounts`)? Sorry for the delay. Thanks!

**Comment by morloderex** [comment]
@jyggen Corrected the namespaces in the last commit! :)

**Comment by jyggen** [comment]
Thanks!

**Pull request merged**
